theme: jekyll-theme-slate
title: The Digital Twin Laboratory Project
description: A digital twin runtime software system
show_downloads: false
github:
  repository_url: https://github.com/DTLaboratory
